server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency, but
        # still good to add it here for better readability
        enabled: false
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
        # Use ip address rather than hostname during registration.
        prefer-ip-address: true
    gateway:
      routes:
        - id: alerts
          uri: lb://alerts/
          predicates:
            - Path=/alerts/recent/**
        - id: authentication
          uri: lb://authentication/
          predicates:
            - Path=/auth/login,/auth/register
        - id: entries
          uri: lb://entries/
          predicates:
            - Path=/entries,/entries/last/**
        - id: stats
          uri: lb://stats/
          predicates:
            - Path=/stats/state/week/**,/stats/emotion/week/top/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedHeaders:
              - '*'
            allowedMethods:
              - 'GET'
              - 'POST'
              - 'DELETE'
              - 'OPTIONS'
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

# ... route config
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace