server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency, but
        # still good to add it here for better readability
        enabled: false
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
        # Use ip address rather than hostname during registration.
        prefer-ip-address: true
    gateway:
      routes:
        - id: authorization
          uri: lb://authorization/
          predicates:
            - Path=/login,/register
        - id: entrylogging
          uri: lb://entrylogging/
          predicates:
            - Path=/state,/state/statistics/week/**,/state/statistics/last/**
        - id: alerts
          uri: lb://alerts/
          predicates:
            - Path=/alerts/recent/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedHeaders:
              - '*'
            allowedMethods:
              - 'GET'
              - 'POST'
              - 'OPTIONS'
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

# ... route config
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace